### PR TITLE
Bump Minimum PHP version to match core and remove config php as not n…

### PR DESCRIPTION
**Pull request by seamuslee001**
https://lab.civicrm.org/dev/core/-/issues/4812

@totten @colemanw

### CODE REVIEW

**Comment by colemanw** [comment]
@seamuslee001 I think this can be closed because standalone has been moved to core.

@totten @artfulrobot can this repo be archived?

**Comment by demeritcowboy** [comment]
The "users" extension is in core, but at last check this was still needed since it's the first step (non-buildkit install). It's been a whole week since I last tried so I might be wrong, but I still see it here: https://github.com/civicrm/civicrm-buildkit/blob/b014fdf3920e1aa574cb1df5661b32f9f75173be/app/config/standalone-clean/download.sh#L11

**Comment by colemanw** [comment]
@demeritcowboy @artfulrobot can you two duel this out?

**Comment by demeritcowboy** [comment]
I expect @artfulrobot knows best about the latest way to install, but the public demo site is definitely using this, so probably at least buildkit "clean" needs updating. In fact the demo build is failing because of this php version issue https://test.civicrm.org/view/Sites/job/demo.civicrm.org/BLDNAME=smaster,label=www-demo/3616/console

**Comment by totten** [comment]
This is a bit tangential, but...

> (@colemanw) ...can this repo be archived?...
>
> (@artfulrobot) ...Yeah I don't think we need this now...
>
> (@demeritcowboy) ...the public demo site is definitely using this...

I think the problem is that the repo is positioned in a way that's not very useful *for the moment*, but it may be pretty important *in the future*.

The Drupal analogy:

* https://github.com/drupal/drupal (analogous to `civicrm-core.git`) is the *main dev repo*. If you're going to install standalone and *do developer stuff*, then you should use this repo as your starting-point.
* https://github.com/drupal/recommended-project (analogous to `civicrm-standalone.git`) is the *composer-based project template for site-builders*. If you're going to install standalone and *run a production site*, then you should use this repo as your starting-point.

The differences:

* With `drupal/drupal` (`civicrm-core`), it's easy to juggle patches, edit code, revise dependencies. The file-layout is a little less "hardened". Its a little awkward if you want to add-on other things via composer (eg `composer require ...drush...`).
* With `drupal/recommended-project` (`civicrm-standalone`), it's easy to mix-in your preferred add-ons and periodically run `composer update`. And the file-layout is a little more "hardened".

During the original push for D8-alpha, devs did not use `drupal/recommended-project`. It didn't exist, and (for core devs) using it would've be an aggravation. But after a few stable releases, it became canonical for site-builders to use a "composer-based project template".

Other observopinions:

* Standalone is at the stage where *everyone is doing developer stuff*.  We don't *need* a project-template for site-builders right now.
* At some point, we will need to cater to site-builder level. And it's fairly easy to keep this project-template going. If we drop it now, then I think it'll be more work later to re-add it.
* Within our ecosystem (where we have people from D7 and D8/D9/D10 and WP and BD), I've encountered... very different opinions about whether `composer` is good for site-building. If you feel that composer is great (or terrible), then keeping the repo is great (or terrible).

**Comment by colemanw** [comment]
Ok, I've merged this since the project is still in use and the change is needed.

**Comment by demeritcowboy** [comment]
Thanks for the clarification, which I'm going to interpret as "this is an opportunity to remove composer completely from civi", which is probably not exactly what you meant but too late now it's in my head and that's all I'm going to remember from this thread. (grin)

**Pull request merged**
